// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
   schema: 'prisma/schema.prisma',
   migrations: {
      path: 'prisma/migrations',
   },
   datasource: {
      url: 'sqlserver://85.10.211.22:1433;database=my-app;user=sa;password=Likeitornot1212;trustServerCertificate=true;',
   },
});
